const GameConst = {
    UPDATE_RIGHT: 'UPDATE_RIGHT',
    UPDATE_WRONG: 'UPDATE_WRONG',
    UPDATE_INPUT: 'UPDATE_INPUT',
    UPDATE_MATCH_ID: 'UPDATE_MATCH_ID',
    UPDATE_PARAGRAPH: 'UPDATE_PARAGRAPH',
    GAME_OVER: 'GAME_OVER',
    COMPLETE: 'COMPLETE',
    GAME_CLEAR: 'GAME_CLEAR'
}

export default GameConst