const GameConst = {
    UPDATE_RIGHT: 'UPDATE_RIGHT',
    UPDATE_WRONG: 'UPDATE_WRONG',
    UPDATE_INPUT: 'UPDATE_INPUT',
    UPDATE_MATCH_ID: 'UPDATE_MATCH_ID',
    GAME_OVER: 'GAME_OVER'
}

export default GameConst