const UserConst = {
  UPDATE_NAME: 'UPDATE_NAME',
  UPDATE_EMAIL: 'UPDATE_EMAIL',
  UPDATE_USER_ID: 'UPDATE_USER_ID',
  TOGGLE_LOGGED_IN: 'TOGGLE_LOGGED_IN',
  USER_CLEAR: 'USER_CLEAR'
}

export default UserConst